[build]
  command = "bun install && bun run build"
  buildplan = '''
  {
    "providers": ["node", "bun"],
    "useNode": false,
    "useBun": true
  }
  '''

[start]
  command = "bun run start"
  port = 3000

[vars]
  NODE_ENV = "production"
  PORT = "3000"
